### case: login success
POST /auth/login
Content-Type: application/json

{
    "username": "sl002",
    "password": "abc1234"
}

### case: not found username
POST /auth/login
Content-Type: application/json

{
    "username": "NOT_FOUND",
    "password": "abc1234"
}

### case: wrong password
POST /auth/login
Content-Type: application/json

{
    "username": "sl002",
    "password": "WRONG_PASS"
}